### PR TITLE
Making it compile and run for node 12+ and electron 6+

### PR DESCRIPTION
**Pull request by thiagoelg**
This was my first time coding for a node and, specially, coding in c++ (for v8), so any feedback is appreciated.

These changes are mostly me banging my head to make this compile and run for the latest node and electron versions without breaking older ones.

As you can see the `macros.hh` file is kind of messy, as I was modifying it as things started to work or break.

With these changes this lib is able to compile from node v0.12 up to node v12, along with electron 1.2.8 up to 6.0.7 (and probably later), though I was not able to test for every version.

Compilations via node versions pre v6 are not possible, but `node-pre-gyp` is able to compile them using the `--target` flag and getting the correct headers.

I tested for electron 1.7.2 and 6.0.7 and `getPrinters` and `printDirect` are working correctly.

Even if this is not merged, hopefully it'll help others updating node-printer to support more recent node releases.

_I published this under @thiagoelg/node-printer on npm._

### CODE REVIEW

**Comment by ekoeryanto** [comment]
I released it with prebuild for my own usage https://github.com/ekoeryanto/node-printer.

thanks @thiagoelg

**Comment by iamtomcat** [comment]
@ekoeryanto I couldn't get the pre-built libraries for electron 6 to run. Kept saying it was build for node version 48. Also I'm on macos.

**Comment by christxph** [comment]
@iamtomcat Try setting `buildDependenciesFromSource: true` in the `build` block in your `package.json`

**Comment by ekoeryanto** [comment]
@iamtomcat I tried electron 6 build with electron builder yesterday, it works.

**Comment by iamtomcat** [comment]
@ekoeryanto Cool, yeah I'm new to electron so just figuring things out. Is there anything you have to set to make sure it grabs the correct version. I've done the electron-rebuild and that's what seems to be getting the wrong package.

**Comment by ekoeryanto** [comment]
@iamtomcat, can you create an issue in the repo, please?

**Comment by ekoeryanto** [comment]
Hi @thiagoelg 
I tried to compile it with electron 7 but it throws this error
```
/tmp/prebuild/electron/7.0.0/include/node/v8.h:3458:37: note:   candidate expects 3 arguments, 2 provided
../src/node_printer_posix.cc: In function ‘void getSupportedPrintFormats(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/node_printer_posix.cc:446:69: error: no matching function for call to ‘v8::Array::Set(int, v8::Local<v8::String>)’
         result->Set(i++, V8_STRING_NEW_UTF8(itFormat->first.c_str()));

```

**Comment by thiagoelg** [comment]
Hmm... I never got to test with Electron 7, there must be some new V8 API changes. I might take a look next weekend.
The current implementation of the macros used are way too sensitive to API changes :/

**Comment by thiagoelg** [comment]
Hey @ekoeryanto, I made it compile for Electron 7, not sure if still works, didn't have time to test, but you can check it here:
https://github.com/thiagoelg/node-printer/pull/7

Also, I borrowed your changes to make it possible to use prebuild. Thanks!

**Comment by ekoeryanto** [comment]
Hi, @thiagoelg I'm happy you published your, I am going to archive mine and use yours.

**Comment by aalvarez255** [comment]
Hi @thiagoelg, I can't make your repo work with electron 7. I'm missing v75 node version (node-printer-v0.5.2-electron-v75-win32-x64.tar.gz).

@ekoeryanto did you manage to get it working with electron 7?

Thanks.

**Comment by thiagoelg** [comment]
@aalvarez255 Yeah, appveyor didn't build for electron 7 for some reason. I built it manually and uploaded it to the 0.5.2 release.
Can you try again?

**Comment by aalvarez255** [comment]
@thiagoelg it's working fine now. Thanks :)

**Comment by aalvarez255** [comment]
@tojocky could you publish updated master branch to npm please? thanks :)

**Comment by thiagoelg** [comment]
I've made some new changes (based on the work from @ekoeryanto) on my fork that makes publishing prebuilt packages for all node/electron versions easier. I can make a new PR here with those changes if @tojocky agrees :)

**Comment by tojocky** [comment]
> @tojocky could you publish updated master branch to npm please? thanks :)

Please check v0.4.0 can work with node v13 as well.

**Comment by tojocky** [comment]
> I've made some new changes (based on the work from @ekoeryanto) on my fork that makes publishing prebuilt packages for all node/electron versions easier. I can make a new PR here with those changes if @tojocky agrees :)

please do

**Pull request merged**
